Repository heyitsmass/BayView, pull requests merged in 2023-11, with the labels that each got.

#52 BayPI Interface Files
  .gitignore
  src/api/README.md
  src/api/baypi.ini
  src/api/lib/__init__.py
  src/api/lib/abc.py
  src/api/lib/app.py
  src/api/lib/loop.py
  src/api/lib/otp.py
  src/api/lib/routes.py
  src/api/main.py
  src/api/requirements.txt
  src/api/tests/test_driver.py
  src/api/tests/test_routes.py
Labels: bAyPI

#67 Top Bar Navigation and Animation Updates
  .gitignore
  package-lock.json
  package.json
  src/app/globals.css
  src/app/home/[id]/page.module.css
  src/app/home/[id]/page.tsx
  src/app/home/layout.tsx
  src/components/Animations/AnimatePresenceComponent/index.tsx
  src/components/HomePage/Card/card.module.css
  src/components/HomePage/Card/index.tsx
  src/components/HomePage/TopBar/index.tsx
  src/components/HomePage/TopBar/topbar.module.css
  src/components/Input/input.module.css
  tailwind.config.ts
Labels: website

#69 Add Flight Component to Home
  src/app/home/[id]/page.tsx
  src/components/HomePage/Card/FlightCard/index.tsx
Labels: website

#78 Pull request for EmailNotifier class Implementation and test file.
  package-lock.json
  package.json
  src/types/EmailNotifier.test.ts
  src/types/ItineraryManager.ts
  vitest.config.ts
Labels: required

#84 SMSNotifier Implementation.
  package-lock.json
  package.json
  src/lib/notifier/Sms.ts
  src/types/SMSNotifier.test.ts
Labels: enhancement

#88 Flight State Updates and API Integration
  src/app/home/page.tsx
  src/components/Animations/AnimatePresenceComponent/animationsPresenceComponent.test.tsx
  src/components/Animations/AnimatePresenceComponent/index.tsx
  src/components/Button/button.module.css
  src/components/Button/index.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Book.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Confirmed.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Search.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Select.tsx
  src/components/HomePage/Card/FlightCard/Testing/__snapshots__/flightCard.test.tsx.snap
  src/components/HomePage/Card/FlightCard/Testing/flightCard.test.tsx
  src/components/HomePage/Card/FlightCard/__snapshots__/flightCard.test.tsx.snap
  src/components/HomePage/Card/FlightCard/flightActions.ts
  src/components/HomePage/Card/FlightCard/flightInterfaces.ts
  src/components/HomePage/Card/FlightCard/flightState.ts
  src/components/HomePage/Card/FlightCard/index.tsx
  src/components/HomePage/Card/card.module.css
  src/components/HomePage/Card/cardCollapseContext.ts
  src/components/HomePage/Card/index.tsx
  src/components/HomePage/TopBar/index.tsx
  src/components/Select/index.tsx
  src/components/Select/select.module.css
Labels: enhancement, website

#91 Calendar Input Refactor / Implementation & Bug Fix
  src/components/HomePage/Card/DiningCard/index.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Confirmed.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Search.tsx
  src/components/HomePage/Card/FlightCard/Presentations/Select.tsx
  src/components/HomePage/Card/LodgingCard/index.tsx
  src/components/Input/BayviewCalendar/calendar.css
  src/components/Input/BayviewCalendar/index.tsx
  src/components/Input/index.tsx
Labels: enhancement, website, bugfix
