Repository heyitsmass/BayView, pull requests merged in 2023-10, with the labels that each got.

#46 Various Updates to be linked to Issues later
  next.config.mjs
  package-lock.json
  package.json
  src/app/GoogleProvider.tsx
  src/app/Handler.ts
  src/app/Provider.tsx
  src/app/auth/login/layout.css
  src/app/auth/login/layout.tsx
  src/app/auth/login/page.module.css
  src/app/auth/login/page.tsx
  src/app/auth/logout/route.ts
  src/app/globals.css
  src/app/home/[id]/page.tsx
  src/app/home/guest/page.tsx
  src/app/home/layout.css
  src/app/home/layout.tsx
  src/app/home/login/components/Input/index.tsx
  src/app/home/login/page.module.css
  src/app/home/login/page.tsx
  src/app/layout.tsx
  src/app/services/auth/google.ts
  src/app/services/auth/local.ts
  src/app/services/auth/utils.ts
  src/app/services/constants.ts
  src/components/Button/button.module.css
  src/components/Button/index.tsx
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  src/context/index.ts
  src/instrumentation.ts
  src/models/CoordinatedItinerary.ts
  src/models/Event.ts
  src/models/Itinerary.ts
  src/models/User.ts
  src/types/CoordinatedItinerary.ts
  src/types/Event.ts
  src/types/Group.ts
  src/types/Itinerary.ts
  src/types/ItineraryManager.ts
  src/types/User.ts
  tailwind.config.ts
Labels: core, group, manager, coordinated, website

#45 made new directory for the admin and login directory for login page. …
  src/app/admin/layout.css
  src/app/admin/layout.tsx
  src/app/admin/login/layout.css
  src/app/admin/login/layout.tsx
  src/app/admin/login/page.module.css
  src/app/admin/login/page.tsx
Labels: core, required, website

#55 Global Font Update to Barlow
  .gitignore
  package-lock.json
  src/app/admin/login/page.module.css
  src/app/fonts.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/Input/input.module.css
Labels: website

#51 added a handler.ts file for use in the login process, also improved t…
  src/app/admin/layout.css
  src/app/admin/layout.tsx
  src/app/admin/login/layout.css
  src/app/admin/login/page.module.css
Labels: website

#56 implemented admin dashboard sidebar.
  src/app/admin/dashboard/layout.css
  src/app/admin/dashboard/layout.tsx
  src/app/admin/dashboard/page.tsx
Labels: enhancement, required, website

#59 Input Components, Home and Global Style Updates
  src/app/admin/login/page.tsx
  src/app/globals.css
  src/app/home/[id]/page.module.css
  src/app/home/[id]/page.tsx
  src/app/home/layout.css
  src/app/home/page.module.css
  src/app/home/page.tsx
  src/components/Button/button.module.css
  src/components/Button/index.tsx
  src/components/HomePage/Card/card.module.css
  src/components/HomePage/Card/index.tsx
  src/components/Input/InputPair/index.tsx
  src/components/Input/InputPair/inputpair.module.css
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  tailwind.config.ts
Labels: enhancement, website
